    </div>
<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/Sticky_navbar.js"></script>
    <script type="text/javascript" src="/js/loader.js"></script>
    <div class="footer">
        <div class="footer-title">
            <a href="https://discord.gg/MJ2EfZG">
                <img id="bfSquad" src="../../images/Site/BFSquadIcon.png" alt="BFSquad">
            </a>
            <header class="footer-header">gta <span style="color: red">5 rp</span> helper</header>
            <header class="footer-header">Copyright &copy; <?php echo date("Y"); ?> <span style="color: red">gta5rp-helper.ru</span></header>
        </div>
    </div>
</body>
</html>