<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">
    <title>GTA - <?php echo $view->pageTitle; ?></title>
</head>
    <div class="header" id="myHeader">
     <div id="header_back">
        <div id="empty">
        </div>
        <div id="background_header">
            <header id="title">gta <span style="color: red">5 rp</span> helper</header>
        </div>
        <div id="empty1">
        </div>
        <div id="background_header2">
            <header id="title2">bf <span style="color: red">squad</span></header>
        </div>
          <div id="empty">
            </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light" id="navbar">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="../../index.php">Home <span class="sr-only">(current)</span></a>
                    <a class="nav-item nav-link" href="../../cars.php">car list</a>
                    <a class="nav-item nav-link" href="../../weapons.php">gun list</a>
                    <a class="nav-item nav-link" href="../../interior.php">interior list</a>
                </div>
            </div>
        </nav>
     </div>
    </div>
<body>
    <div id="loader"></div>