<?php
require_once("template/header.phtml")
?>
<div id="content">
    <div id="empty">
    </div>
    <div id="container">
        <div id="interior-container-background">
            <div id="empty-space">
            </div>
            <div id="interior-left-container">
                <button class="btn3" id="all">все</button>
                <button class="btn3" id="all">ангары</button>
                <button class="btn3" id="all">полиция</button>
                <button class="btn3" id="all">медики</button>
                <button class="btn3" id="all">дома</button>
                <button class="btn3" id="all">отели</button>
                <button class="btn3" id="all">хранилище</button>
            </div>
            <div id="interior-left-pointer">
                <img id="interior-left-arrow" src="../images/Site/LeftArrow.png" alt="left-arrow">
            </div>
            <div id="interior-right-container">
                <div class="row" id="interior-main-images">
                    <div class="column" id="interior-image1">
                    </div>
                    <div class="column" id="interior-image2">
                    </div>
                    <div class="column" id="interior-image3">
                    </div>
                    <div class="column" id="interior-image4">
                    </div>
                    <div class="column" id="interior-image5">
                    </div>
                    <div class="column" id="interior-image6">
                    </div>
                    <div class="column" id="interior-image7">
                    </div>
                    <div class="column" id="interior-image8">
                    </div>
                    <div class="column" id="interior-image9">
                    </div>
                </div>
                <div id="interior-right-pointer">
                    <img id="interior-right-arrow" src="../images/Site/RightArrow.png" alt="right-arrow">
                </div>
            </div>
        </div>
    </div>
</div>
<?php
require_once('template/footer.phtml');