<?php
require_once ("template/header.phtml");
?>
<div id="content">
    <div id="empty">
    </div>
    <div id="container">
        <div id="weapon-container-background">
            <div id="empty-space">
            </div>
            <div id="weapon-left-container">
                <button class="btn2" id="all">все</button>
                <button class="btn2" id="all">одноручные</button>
                <button class="btn2" id="all">дробовики</button>
                <button class="btn2" id="all">машин-ганы</button>
                <button class="btn2" id="all">штурмовые</button>
                <button class="btn2" id="all">снайперки</button>
                <button class="btn2" id="all">тяжелые</button>
                <button class="btn2" id="all">ближний бой</button>
                <button class="btn2" id="all">метательные</button>
                <button class="btn2" id="all">можно сидеть</button>
            </div>
            <div id="weapon-left-pointer">
                <img id="weapon-left-arrow" src="../images/Site/LeftArrow.png" alt="left-arrow">
            </div>
            <div id="weapon-right-container">
                <div class="row" id="weapon-main-images">
                    <div class="column" id="weapon-image1">
                    </div>
                    <div class="column" id="weapon-image2">
                    </div>
                    <div class="column" id="weapon-image3">
                    </div>
                    <div class="column" id="weapon-image4">
                    </div>
                    <div class="column" id="weapon-image5">
                    </div>
                    <div class="column" id="weapon-image6">
                    </div>
                    <div class="column" id="weapon-image7">
                    </div>
                    <div class="column" id="weapon-image8">
                    </div>
                    <div class="column" id="weapon-image9">
                    </div>
                </div>
                <div id="weapon-right-pointer">
                    <img id="weapon-right-arrow" src="../images/Site/RightArrow.png" alt="right-arrow">
                </div>
            </div>
        </div>
    </div>
</div>
<?php
require_once ("template/footer.phtml");
?>
